tabWidth: 4
singleQuote: false
semi: true
printWidth: 100
trailingComma: "ES5"
bracketSpacing: true
arrowParens: "always"
endOfLine: "auto"
quoteProps: "as-needed"
jsxSingleQuote: false
jsxBracketSameLine: false
useTabs: false
insertPragma: false
requirePragma: false
proseWrap: "preserve"
htmlWhitespaceSensitivity: "css"
vueIndentScriptAndStyle: false
